services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4400:80"
  node-app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=4400
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: node index.js
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    image: redis

volumes:
  mongo-db: