GET http://localhost:4400/api/v1/

### Get all players
GET http://localhost:4400/api/v1/players HTTP/1.1

### Create ${user_numbers} new fake players by setting queries: user_numbers, is_this_week_active
POST http://localhost:4400/api/v1/players?user_numbers=100&is_this_week_active=true HTTP/1.1
content-type: application/json

### Delete all players
DELETE  http://localhost:4400/api/v1/players HTTP/1.1
